#modeals/fundamentals_td_ameritrade.py
from sqlalchemy import Column, String, Integer, Float, DateTime, BigInteger, Index
from support.base import Base
import datetime

class Symbol_Fundamentals_TD_Ameritrade(Base):
    __tablename__ = 'symbol_fundamentals_td_ameritrade'
    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String, index=True)
    timestamp = Column(DateTime, index=True)
    high52 = Column(Float)
    low52 = Column(Float)
    dividendAmount = Column(Float)
    dividendYield = Column(Float)
    dividendDate = Column(DateTime)
    peRatio = Column(Float)
    pegRatio = Column(Float)
    pbRatio = Column(Float)
    prRatio = Column(Float)
    pcfRatio = Column(Float)
    grossMarginTTM = Column(Float)
    grossMarginMRQ = Column(Float)
    netProfitMarginTTM = Column(Float)
    netProfitMarginMRQ = Column(Float)
    operatingMarginTTM = Column(Float)
    operatingMarginMRQ = Column(Float)
    returnOnEquity = Column(Float)
    returnOnAssets = Column(Float)
    returnOnInvestment = Column(Float)
    quickRatio = Column(Float)
    currentRatio = Column(Float)
    interestCoverage = Column(Float)
    totalDebtToCapital = Column(Float)
    ltDebtToEquity = Column(Float)
    totalDebtToEquity = Column(Float)
    epsTTM = Column(Float)
    epsChangePercentTTM = Column(Float)
    epsChangeYear = Column(Float)
    epsChange = Column(Float)
    revChangeYear = Column(Float)
    revChangeTTM = Column(Float)
    revChangeIn = Column(Float)
    sharesOutstanding = Column(BigInteger)
    marketCapFloat = Column(Float)
    marketCap = Column(Float)
    bookValuePerShare = Column(Float)
    shortIntToFloat = Column(Float)
    shortIntDayToCover = Column(Float)
    divGrowthRate3Year = Column(Float)
    dividendPayAmount = Column(Float)
    dividendPayDate = Column(DateTime)
    beta = Column(Float)
    vol1DayAvg = Column(BigInteger)
    vol10DayAvg = Column(BigInteger)
    vol3MonthAvg = Column(BigInteger)
    cusip = Column(String)
    description = Column(String)
    exchange = Column(String)
    assetType = Column(String)
    source = Column(String, nullable=False)
    last_updated = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)
    updated_by = Column(String, nullable=False)
    
# Create indexes
#Index('ix_symbol_fundamentals_td_ameritrade_symbol', Symbol_Fundamentals_TD_Ameritrade.symbol)
#Index('ix_symbol_fundamentals_td_ameritrade_timestamp', Symbol_Fundamentals_TD_Ameritrade.timestamp)